print('What do you get when you cross a snowman with a vampire?')
raw_input()
print('Frostbite!')
raw_input()
print('What do dentists call an astronauts cavity?')
raw_input()
print('A black hole!')
raw_input()
print('knock knock')
raw_input()
print('Interupting cow.')
raw_input()
print('Interupting cow wh-')
print('MOO!')
